version: "3.8"

services:
  # Redis
  redis:
    image: redis:alpine
    container_name: wghsoga_redis

  # Database Postgres
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wghsoga_postgres
      - POSTGRES_USER=wghsoga_postgres
      - POSTGRES_PASSWORD=wghsoga_postgres
    container_name: wghsoga_postgres_db

  # Django Application
  wghsoga_app:
    build:
      context: .
    volumes:
      - .:/wghsoga_django
      - ./static_cdn:/var/lib/static_cdn
    ports:
      - 6060:6060
    container_name: wghsoga_app
    command: python manage.py runserver 0.0.0.0:6060
    depends_on:
      - db

  # React Application
  wghsoga_frontend:
    build:
      context: ../wghsoga_frontend  # Adjust the path to your React app
    ports:
      - "7000:7000"  # Map to the host's port
    environment:
      - REACT_APP_API_URL=http://wghsoga_app:6060  # API URL for Django service

  # Celery Worker
  celery:
    restart: always
    build:
      context: .
    command: celery -A wghsoga_project worker -l DEBUG
    volumes:
      - .:/wghsoga_django
    container_name: wghsoga_celery
    depends_on:
      - db
      - redis
      - wghsoga_app

  # Celery Beat
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A wghsoga_project beat -l DEBUG
    volumes:
      - .:/wghsoga_django
    container_name: wghsoga_celery_beat
    depends_on:
      - db
      - redis
      - wghsoga_app

volumes:
  static_cdn:
